file:
  upload-dir: uploads
spring:
  mail:
    host: smtp.qq.com
    username: 3499508634@qq.com
    password: hddhucgnnljwchbh
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 数据库
  datasource:
    username: root
    password: Wei.Li.Laba00
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  rabbitmq:
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080

# logging:
#   level:
#     root: INFO
#     org.springframework: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
  show-actuat: true
